export const SYSTEM_CONSTANTS = {
  HUB_DISCREPANCY_TOLERANCE_PERCENT: 5.0, // 5% maximum allowable weight discrepancy
  OTP_EXPIRY_SECONDS: 300, // 5 minutes
  JWT_ACCESS_EXPIRY: '15m',
  JWT_REFRESH_EXPIRY: '7d',
  DEFAULT_SERVICE_RADIUS_KM: 10.0,
  CPCB_RECORD_RETENTION_YEARS: 5,
} as const;

export const WASTE_CATEGORIES = {
  PCB_HIGH_GRADE: 'PCB_HIGH_GRADE',
  PCB_LOW_GRADE: 'PCB_LOW_GRADE',
  LITHIUM_BATTERY: 'LITHIUM_BATTERY',
  DISPLAY_UNIT: 'DISPLAY_UNIT',
  MIXED_APPLIANCE: 'MIXED_APPLIANCE',
  PLASTIC_CASING: 'PLASTIC_CASING',
  METALS: 'METALS',
  OTHER_E_WASTE: 'OTHER_E_WASTE',
} as const;

export type WasteCategoryCode = keyof typeof WASTE_CATEGORIES;
